CREATE TABLE [dbo].[Comment]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Content] VARCHAR(MAX) NOT NULL, 
    [PostDate] DATETIME2 NOT NULL, 
    [UserID] INT NULL, 
    [MovieID] INT NULL
    CONSTRAINT FK_COMMENT_MOVIE FOREIGN KEY (UserID) REFERENCES [User](Id),
    CONSTRAINT FK_COMMENT_USER FOREIGN KEY (MovieID) REFERENCES Movie(Id)
)
